#!/usr/bin/env bash
# Bootstrap MinIO via Docker. Works on macOS (Docker Desktop) and Linux.
# Idempotent — safe to re-run.
#
# What it does:
#   1. Creates the data directory (default: ~/spindle/minio-data).
#   2. Generates root credentials on first run, writes to infra/minio/.env
#      (gitignored). Re-running uses existing creds.
#   3. Starts MinIO via `docker compose up -d`.
#   4. Waits for health, prints connection info.
#
# Override defaults via env:
#   MINIO_DATA_DIR    where bytes live   (default: ~/spindle/minio-data)
#   MINIO_API_PORT    S3 API port        (default: 9000)
#   MINIO_CONSOLE_PORT  web UI port      (default: 9001)
#   MINIO_ROOT_USER   admin user         (default: spindle)
#   MINIO_ROOT_PASSWORD  admin pw        (default: random 40 chars)
#
# Usage:
#   ./bootstrap.sh
#   MINIO_DATA_DIR=/mnt/spindle-artifacts ./bootstrap.sh

set -euo pipefail

cd "$(dirname "$0")"

# ── prerequisites ───────────────────────────────────────────────────
if ! command -v docker >/dev/null; then
  echo "ERROR: docker is not installed."
  echo "  macOS: install Docker Desktop  (https://www.docker.com/products/docker-desktop/)"
  echo "  Linux: curl -fsSL https://get.docker.com | sh"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' (v2) is required. Older 'docker-compose' is not supported."
  exit 1
fi

# ── data directory ──────────────────────────────────────────────────
DATA_DIR="${MINIO_DATA_DIR:-$HOME/spindle/minio-data}"
mkdir -p "$DATA_DIR"

# ── credentials ─────────────────────────────────────────────────────
ENV_FILE=".env"

if [ ! -f "$ENV_FILE" ]; then
  ROOT_USER="${MINIO_ROOT_USER:-spindle}"

  if [ -n "${MINIO_ROOT_PASSWORD:-}" ]; then
    ROOT_PASSWORD="$MINIO_ROOT_PASSWORD"
  else
    # 40-char random alphanumeric password. tr strips bytes that confuse shells
    # or env-var encoders; then truncate to 40.
    ROOT_PASSWORD="$(openssl rand -base64 64 | tr -d '/+=\n' | head -c 40)"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by infra/minio/bootstrap.sh — do not commit.
# Re-run bootstrap.sh to use these; delete this file to regenerate.
MINIO_ROOT_USER=${ROOT_USER}
MINIO_ROOT_PASSWORD=${ROOT_PASSWORD}
MINIO_DATA_DIR=${DATA_DIR}
MINIO_API_PORT=${MINIO_API_PORT:-9000}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT:-9001}
EOF
  chmod 600 "$ENV_FILE"

  echo ""
  echo "── credentials generated ────────────────────────────────────────"
  echo "  saved to $(pwd)/$ENV_FILE  (chmod 600, gitignored)"
  echo "  user:     ${ROOT_USER}"
  echo "  password: ${ROOT_PASSWORD}"
  echo "  ↑ save these somewhere safe — also visible in $ENV_FILE"
  echo "────────────────────────────────────────────────────────────────"
  echo ""
fi

# ── start ───────────────────────────────────────────────────────────
echo "Starting MinIO..."
docker compose up -d

# ── wait for healthy ────────────────────────────────────────────────
API_PORT="$(grep '^MINIO_API_PORT=' "$ENV_FILE" | cut -d= -f2)"
echo -n "Waiting for MinIO to become healthy"
for _ in $(seq 1 30); do
  if curl -fsS "http://localhost:${API_PORT}/minio/health/live" >/dev/null 2>&1; then
    echo " ✓"
    break
  fi
  echo -n "."
  sleep 1
done

CONSOLE_PORT="$(grep '^MINIO_CONSOLE_PORT=' "$ENV_FILE" | cut -d= -f2)"

# Try to print a useful hostname. On Mac, hostname might be e.g. "mac-mini.local";
# on Linux "spark", etc. Falls back to localhost.
HOST_HINT="$(hostname 2>/dev/null || echo localhost)"

cat <<EOF

MinIO is up.

  S3 API:  http://${HOST_HINT}:${API_PORT}    (also: http://localhost:${API_PORT})
  Console: http://${HOST_HINT}:${CONSOLE_PORT}

Credentials are in $(pwd)/${ENV_FILE} (root-only). To view:
  cat $(pwd)/${ENV_FILE}

To stop:    docker compose -f $(pwd)/compose.yaml --env-file $(pwd)/${ENV_FILE} down
To restart: docker compose -f $(pwd)/compose.yaml --env-file $(pwd)/${ENV_FILE} restart
To logs:    docker compose -f $(pwd)/compose.yaml --env-file $(pwd)/${ENV_FILE} logs -f

EOF
